a = int(input("Enter first no.- "))
b = int(input("Enter second no.- "))
print("Addition of a and b ", a+b)
print("Subtraction of a and b ", a-b)
print("Multiplication of a and b ", a*b)
print("Division of a and b ", a/b)